"""Deterministic task receipt shared by terminal and HTML renderers."""

from __future__ import annotations

import fnmatch
import json
import re
from datetime import datetime
from pathlib import PurePosixPath
from typing import Any

from .crypto import key_id, sha256_bytes
from .evidence import evidence_semantic_issue
from .events import verify_log
from .git_state import changed_files, checkpoint_integrity_issue
from .store import RewindError, RewindPaths, project, read_json
from .task import find_task, task_events

DEPENDENCY_PATTERNS = (
    "pyproject.toml",
    "requirements*.txt",
    "poetry.lock",
    "package.json",
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "Cargo.toml",
    "Cargo.lock",
    "go.mod",
    "go.sum",
)

# Generated bytecode caches are snapshot noise, not reviewable changes. They
# stay in checkpoint trees but are excluded from receipt analysis so a test
# run invoked through `rewind run` cannot flag its own cache writes.
CACHE_DIR_NAMES = {"__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache"}
CACHE_SUFFIXES = (".pyc", ".pyo")


def is_cache_artifact(path: str) -> bool:
    normalized = path.replace("\\", "/")
    if normalized.endswith(CACHE_SUFFIXES):
        return True
    return any(part in CACHE_DIR_NAMES for part in normalized.split("/"))


def reviewable_changes(paths: list[str]) -> list[str]:
    return [path for path in paths if not is_cache_artifact(path)]


def path_matches(path: str, pattern: str) -> bool:
    normalized = path.replace("\\", "/")
    while normalized.startswith("./"):
        normalized = normalized[2:]
    candidate = PurePosixPath(normalized)
    if pattern.endswith("/**") and normalized.startswith(pattern[:-3].rstrip("/") + "/"):
        return True
    return fnmatch.fnmatchcase(normalized, pattern) or candidate.match(pattern)


def matches_any(path: str, patterns: list[str] | tuple[str, ...]) -> bool:
    return any(path_matches(path, pattern) for pattern in patterns)


def dependency_files(files: list[str]) -> list[str]:
    return [path for path in files if matches_any(PurePosixPath(path).name, DEPENDENCY_PATTERNS)]


def _elapsed(started_at: str, ended_at: str) -> tuple[int, str]:
    start = datetime.fromisoformat(started_at.replace("Z", "+00:00"))
    end = datetime.fromisoformat(ended_at.replace("Z", "+00:00"))
    seconds = max(0, round((end - start).total_seconds()))
    if seconds < 60:
        return seconds, f"{seconds}s"
    minutes, remainder = divmod(seconds, 60)
    return seconds, f"{minutes}m {remainder:02d}s"


def _test_count(paths: RewindPaths, checks: list[dict[str, Any]]) -> int | None:
    patterns = (
        re.compile(r"(?<!\d)(\d+)\s+passed\b"),
        re.compile(r"\bRan\s+(\d+)\s+tests?\b"),
    )
    for check in reversed(checks):
        if not check["payload"].get("passed") or check["payload"].get("kind") != "test":
            continue
        digest = check["payload"]["evidence_sha256"]
        object_path = paths.objects / digest
        if not object_path.exists():
            continue
        evidence_bytes = object_path.read_bytes()
        if sha256_bytes(evidence_bytes) != digest:
            continue
        try:
            evidence = json.loads(evidence_bytes)
        except (json.JSONDecodeError, UnicodeDecodeError):
            continue
        text = f"{evidence.get('stdout', '')}\n{evidence.get('stderr', '')}"
        for pattern in patterns:
            match = pattern.search(text)
            if match:
                return int(match.group(1))
    return None


def build_receipt(paths: RewindPaths, requested_task_id: str | None = None) -> dict[str, Any]:
    task_id = find_task(paths, requested_task_id)
    log = project(paths)
    log_verification = verify_log(paths.events, log.verify_key)
    relevant = task_events(paths, task_id)
    start = next((event for event in relevant if event["type"] == "task_started"), None)
    if start is None:
        raise RewindError(f"Task start event is missing for {task_id}.")
    checkpoints = [event for event in relevant if event["type"] == "checkpoint_recorded"]
    checks = [event for event in relevant if event["type"] == "command_evidence_recorded"]
    finish = next((event for event in reversed(relevant) if event["type"] == "task_finished"), None)
    if not checkpoints:
        raise RewindError(f"Task {task_id} has no checkpoints.")

    checkpoint_ids: dict[str, list[dict[str, Any]]] = {}
    for event in checkpoints:
        checkpoint_ids.setdefault(str(event["payload"]["checkpoint_id"]), []).append(event)
    checkpoint_issues: list[dict[str, str]] = [
        {
            "level": "L1",
            "code": "duplicate_checkpoint_id",
            "message": (
                f"Checkpoint ID {checkpoint_id} appears {len(events)} times; "
                "recovery by checkpoint ID is ambiguous."
            ),
        }
        for checkpoint_id, events in checkpoint_ids.items()
        if len(events) > 1
    ]

    initial = checkpoints[0]["payload"]
    if finish:
        final_matches = [
            event["payload"]
            for event in checkpoints
            if event["payload"]["checkpoint_id"] == finish["payload"]["final_checkpoint_id"]
            and event["payload"]["commit"] == finish["payload"]["final_commit"]
            and event["payload"]["tree"] == finish["payload"]["final_tree"]
        ]
        if len(final_matches) != 1:
            raise RewindError(
                f"Task {task_id} has no unique checkpoint matching its signed final state."
            )
        final = final_matches[0]
    else:
        final = checkpoints[-1]["payload"]
    changed = reviewable_changes(changed_files(paths.root, initial["tree"], final["tree"]))
    allowed = list(start["payload"]["allowed_paths"])
    within_scope = [path for path in changed if matches_any(path, allowed)]
    outside_scope = [path for path in changed if path not in within_scope]
    dependencies = dependency_files(changed)
    recorded_protected = start["payload"].get("protected_globs")
    if isinstance(recorded_protected, list) and all(
        isinstance(pattern, str) for pattern in recorded_protected
    ):
        protected_patterns = list(recorded_protected)
    else:
        # Legacy task logs predate signed task-level protected globs.
        config = read_json(paths.config, {})
        protected_patterns = list(config.get("protected_globs", []))
    protected = [path for path in changed if matches_any(path, protected_patterns)]

    evidence_issues: list[dict[str, str]] = []
    verified_evidence_ids: set[str] = set()
    for check in checks:
        digest = str(check["payload"].get("evidence_sha256", ""))
        object_path = paths.objects / digest
        if len(digest) != 64 or any(character not in "0123456789abcdef" for character in digest):
            evidence_issues.append(
                {
                    "level": "L1",
                    "code": "invalid_evidence_reference",
                    "message": "Recorded evidence reference is not a SHA-256 digest.",
                }
            )
        elif not object_path.is_file():
            evidence_issues.append(
                {
                    "level": "L1",
                    "code": "missing_evidence",
                    "message": f"Evidence {digest[:12]} is missing.",
                }
            )
        else:
            evidence_bytes = object_path.read_bytes()
            if sha256_bytes(evidence_bytes) != digest:
                evidence_issues.append(
                    {
                        "level": "L1",
                        "code": "evidence_tampered",
                        "message": f"Evidence {digest[:12]} failed its SHA-256 check.",
                    }
                )
            else:
                semantic_issue = evidence_semantic_issue(check["payload"], evidence_bytes)
                if semantic_issue:
                    evidence_issues.append(
                        {
                            "level": "L2",
                            "code": "evidence_payload_mismatch",
                            "message": f"Evidence {digest[:12]} is inconsistent: {semantic_issue}.",
                        }
                    )
                else:
                    verified_evidence_ids.add(str(check["content_id"]))

    incomplete_check_issues: list[dict[str, str]] = []
    for checkpoint in checkpoints:
        payload = checkpoint["payload"]
        if payload.get("kind") != "pre_check":
            continue
        has_evidence = any(
            check["payload"].get("checkpoint_id") == payload.get("checkpoint_id")
            and check["payload"].get("checkpoint_commit") == payload.get("commit")
            and check["payload"].get("tree") == payload.get("tree")
            for check in checks
        )
        if not has_evidence:
            incomplete_check_issues.append(
                {
                    "level": "L0",
                    "code": "incomplete_check_attempt",
                    "message": (
                        f"Recorded check attempt at {payload.get('checkpoint_id')} "
                        "did not produce command evidence."
                    ),
                }
            )

    recorded_passing = [check for check in checks if check["payload"].get("passed")]
    passing = [
        check
        for check in recorded_passing
        if str(check["content_id"]) in verified_evidence_ids
    ]
    last_passing = passing[-1] if passing else None
    last_check = checks[-1] if checks else None
    after_evidence = (
        reviewable_changes(
            changed_files(paths.root, last_passing["payload"]["tree"], final["tree"])
        )
        if last_passing
        else []
    )
    recovery = None
    recovery_kind = None
    recovery_issue = None
    if last_passing and not evidence_issues:
        checkpoint_id = str(last_passing["payload"]["checkpoint_id"])
        candidates = checkpoint_ids.get(checkpoint_id, [])
        exact_matches = [
            event["payload"]
            for event in candidates
            if event["payload"].get("commit") == last_passing["payload"].get("checkpoint_commit")
            and event["payload"].get("tree") == last_passing["payload"].get("tree")
        ]
        if len(candidates) == 1 and len(exact_matches) == 1:
            candidate = exact_matches[0]
            integrity_issue = checkpoint_integrity_issue(
                paths.root,
                commit=str(candidate["commit"]),
                tree=str(candidate["tree"]),
                ref=str(candidate["ref"]),
            )
            if integrity_issue:
                recovery_issue = {
                    "level": "L1",
                    "code": "checkpoint_integrity_failed",
                    "message": f"Passing evidence checkpoint is not recoverable: {integrity_issue}.",
                }
                checkpoint_issues.append(recovery_issue)
            else:
                recovery = candidate
                recovery_kind = str(last_passing["payload"].get("kind", "check"))
        else:
            recovery_issue = {
                "level": "L1",
                "code": "ambiguous_recovery_checkpoint",
                "message": (
                    f"Passing evidence references checkpoint {checkpoint_id}, but that checkpoint "
                    "cannot be resolved uniquely by ID, commit, and tree."
                ),
            }
            checkpoint_issues.append(recovery_issue)

    if recovery:
        evidence_label = "test" if recovery_kind == "test" else "check"
        recovery_summary = (
            f"{recovery['checkpoint_id']} has integrity-verified passing {evidence_label} evidence"
        )
        recovery_status = "READY"
    elif recovery_issue:
        recovery_summary = recovery_issue["message"]
        recovery_status = "FAIL"
    elif evidence_issues:
        recovery_summary = "Recovery is unavailable because recorded evidence failed integrity verification"
        recovery_status = "NONE"
    else:
        recovery_summary = "No integrity-verified passing-evidence checkpoint is available"
        recovery_status = "NONE"

    unfinished = finish is None
    latest_check_failed = bool(last_check and not last_check["payload"].get("passed"))
    evidence_failed = bool(
        evidence_issues
        or incomplete_check_issues
        or latest_check_failed
        or (not passing and not unfinished)
    )
    signals: list[dict[str, Any]] = [
        {
            "key": "scope",
            "label": "Scope",
            "status": "WARN" if outside_scope else "PASS",
            "summary": (
                f"{len(outside_scope)} file{'s' if len(outside_scope) != 1 else ''} outside declared scope"
                if outside_scope
                else "All changed files are within declared scope"
            ),
            "files": outside_scope,
        },
        {
            "key": "evidence",
            "label": "Evidence",
            "status": (
                "FAIL"
                if evidence_failed
                else "WARN"
                if unfinished or after_evidence
                else "PASS"
            ),
            "summary": (
                evidence_issues[0]["message"]
                if evidence_issues
                else incomplete_check_issues[0]["message"]
                if incomplete_check_issues
                else "The most recent recorded check failed"
                if latest_check_failed
                else (
                    "Task is active; this receipt covers recorded checkpoints only. "
                    "Run `rewind finish` to capture and evaluate the final working state"
                )
                if unfinished
                else "No integrity-verified successful check was recorded"
                if not passing
                else f"{len(after_evidence)} file{'s' if len(after_evidence) != 1 else ''} changed after the last passing check"
                if after_evidence
                else "Final state matches the last passing check"
            ),
            "files": after_evidence,
        },
        {
            "key": "dependencies",
            "label": "Dependencies / protected",
            "status": "WARN" if dependencies or protected else "PASS",
            "summary": (
                f"{len(dependencies)} dependency and {len(protected)} protected-path changes"
                if dependencies or protected
                else "No dependency or protected-path changes"
            ),
            "files": sorted(set(dependencies + protected)),
        },
        {
            "key": "recovery",
            "label": "Recovery",
            "status": recovery_status,
            "summary": recovery_summary,
            "files": [],
        },
    ]
    review_items = sum(signal["status"] in {"WARN", "FAIL"} for signal in signals)
    if (
        not log_verification.valid
        or evidence_issues
        or incomplete_check_issues
        or checkpoint_issues
        or (not passing and not unfinished)
        or latest_check_failed
    ):
        outcome = "Needs attention"
        outcome_key = "fail"
    elif unfinished:
        outcome = "In progress"
        outcome_key = "warn"
    elif review_items:
        outcome = "Completed with items to review"
        outcome_key = "warn"
    else:
        outcome = "Completed"
        outcome_key = "pass"

    ended_at = (finish or checkpoints[-1])["recorded_at"]
    elapsed_seconds, elapsed_display = _elapsed(start["recorded_at"], ended_at)
    timeline = [
        {
            "sequence": event["sequence"],
            "recorded_at": event["recorded_at"],
            "type": event["type"],
            "actor": event["actor"],
            "content_id": event["content_id"],
            "payload": event["payload"],
        }
        for event in relevant
    ]
    return {
        "schema": "rewind.receipt.v1",
        "task_id": task_id,
        "intent": start["payload"]["intent"],
        "allowed_paths": allowed,
        "protected_globs": protected_patterns,
        "started_at": start["recorded_at"],
        "ended_at": ended_at,
        "elapsed_seconds": elapsed_seconds,
        "elapsed_display": elapsed_display,
        "finished": finish is not None,
        "outcome": outcome,
        "outcome_key": outcome_key,
        "review_item_count": review_items,
        "signals": signals,
        "changed_files": changed,
        "within_scope": within_scope,
        "outside_scope": outside_scope,
        "dependency_files": dependencies,
        "protected_files": protected,
        "changed_after_passing_evidence": after_evidence,
        "checks": [event["payload"] for event in checks],
        "passing_check_count": len(passing),
        "recorded_passing_check_count": len(recorded_passing),
        "test_count": (
            _test_count(paths, [last_passing])
            if last_passing and last_passing["payload"].get("kind") == "test"
            else None
        ),
        "initial_checkpoint": initial,
        "final_checkpoint": final,
        "recommended_recovery": recovery,
        "recommended_recovery_kind": recovery_kind,
        "timeline": timeline,
        "audit": {
            "log_valid": log_verification.valid,
            "event_count": len(log_verification.events),
            "issues": [
                {
                    "level": issue.level,
                    "code": issue.code,
                    "message": issue.message,
                    "sequence": issue.sequence,
                }
                for issue in log_verification.issues
            ]
            + evidence_issues
            + incomplete_check_issues
            + checkpoint_issues,
            "key_id": key_id(log.verify_key),
            "threat_model": "Tamper-evident assertions under one trusted local recorder key.",
        },
    }
